name: rust-axum

services:
  db:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  pgdata: