edition = "2024"
unstable_features = true

max_width = 100

#group_imports = "StdExternalCrate"
imports_granularity = "Module"
#imports_layout = "Mixed"

blank_lines_upper_bound = 2

#comment_width = 100
#wrap_comments = true
format_code_in_doc_comments = true
